image: node:12-alpine

stages:
  - install
  - lint
  - test
  - deploy

cache:
  paths:
    - node_modules/

install:
  stage: install
  script:
    - yarn install

lint:
  stage: lint
  script:
    - yarn lint:js . --format junit --output-file ./reports/lint.xml
    - yarn lint:md .
  artifacts:
    reports:
      junit: 'reports/lint.xml'
    expire_in: 30 days

unit:
  stage: test
  script: |
    JEST_JUNIT_OUTPUT=reports/unit.xml \
    yarn test:ci \
    --coverageDirectory ./reports/unit-coverage \
    test/unit
  coverage: '/All\sfiles.*?\s+(\d+.\d+)/'
  artifacts:
    reports:
      junit: 'reports/unit.xml'
    paths:
      - reports/unit-coverage
    expire_in: 30 days

# integration:
#   stage: test
#   script: |
#     JEST_JUNIT_OUTPUT=reports/integration.xml \
#     yarn test:ci \
#     --coverageDirectory ./reports/integration-coverage \
#     test/integration
#   coverage: '/All\sfiles.*?\s+(\d+.\d+)/'
#   artifacts:
#     reports:
#       junit: 'reports/integration.xml'
#     paths:
#       - reports/integration-coverage
#     expire_in: 30 days

pages:
  stage: deploy
  dependencies:
    - unit
    # - integration
  script:
    - mv reports/unit-coverage/ public/
    # - mv reports/integration-coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
